### ISSUE TITLE
consider using vek

### ISSUE THREAD

**Issue by josharian** [coder/hnsw#5]
I ran a very quick benchmark, and https://github.com/viterin/vek appears to be ~10x faster for cosine similarity than plain Go on an AVX2 machine.

Given this from the README:

> At 1536 dimensions (OpenAI default), 70% of the query process under default parameters is spent in the distance function.

It seems like using vek could have a pretty big impact.

**Comment by ammario** [comment]
https://github.com/coder/hnsw/commit/c8a7f6c0b86e5b30ac60852bfc94b287c024ef14
